#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Resources

<#
.SYNOPSIS
    Removes orphaned RBAC role assignments from Azure subscriptions and management groups.

.DESCRIPTION
    This script scans all accessible Azure subscriptions and optionally management groups
    for RBAC role assignments that reference deleted (unresolvable) principals 
    (users, groups, service principals). It displays orphaned assignments and prompts for their removal.

.PARAMETER SubscriptionId
    Optional. Specify one or more subscription IDs to scan. If not provided, all accessible subscriptions are scanned.

.PARAMETER IncludeManagementGroups
    Also scan management groups for orphaned role assignments.

.PARAMETER Force
    Skip confirmation prompts and remove all orphaned assignments automatically.

.EXAMPLE
    .\remove-orphanedaccounts.ps1
    Scans all subscriptions and prompts before each deletion.

.EXAMPLE
    .\remove-orphanedaccounts.ps1 -IncludeManagementGroups
    Scans all subscriptions AND management groups.

.EXAMPLE
    .\remove-orphanedaccounts.ps1 -WhatIf
    Shows what orphaned assignments would be removed without actually removing them.

.EXAMPLE
    .\remove-orphanedaccounts.ps1 -SubscriptionId "12345678-1234-1234-1234-123456789abc"
    Scans only the specified subscription.

.EXAMPLE
    .\remove-orphanedaccounts.ps1 -Force
    Removes all orphaned assignments without prompting.

.NOTES
    Author: Generated by GitHub Copilot
    Requires: PowerShell 7.0+, Az.Accounts, Az.Resources modules
    Assumes: User is already logged in to Azure (Connect-AzAccount)
#>

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory = $false, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
    [ValidateNotNullOrEmpty()]
    [string[]]$SubscriptionId,

    [Parameter(Mandatory = $false)]
    [switch]$IncludeManagementGroups,

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

begin {
    # Enforce strict mode - catch common coding errors
    Set-StrictMode -Version Latest
    
    # Stop at first error
    $ErrorActionPreference = 'Stop'
    
    # Script-level variables
    $script:TotalOrphanedCount = 0
    $script:TotalRemovedCount = 0
    $script:TotalSkippedCount = 0
    $script:AllOrphanedAssignments = [System.Collections.Generic.List[PSCustomObject]]::new()

    function Test-AzureConnection {
        <#
        .SYNOPSIS
            Validates that the user is logged in to Azure.
        #>
        [CmdletBinding()]
        [OutputType([bool])]
        param()

        try {
            $context = Get-AzContext -ErrorAction Stop
            if ($null -eq $context -or $null -eq $context.Account) {
                Write-Error "Not logged in to Azure. Please run 'Connect-AzAccount' first."
                return $false
            }
            Write-Host "✓ Connected to Azure as: $($context.Account.Id)" -ForegroundColor Green
            Write-Host "  Tenant: $($context.Tenant.Id)" -ForegroundColor Cyan
            return $true
        }
        catch {
            Write-Error "Failed to verify Azure connection: $_"
            return $false
        }
    }

    function Get-OrphanedRoleAssignments {
        <#
        .SYNOPSIS
            Gets orphaned RBAC role assignments for a subscription.
        #>
        [CmdletBinding()]
        [OutputType([PSCustomObject[]])]
        param(
            [Parameter(Mandatory = $true)]
            [string]$SubscriptionId,

            [Parameter(Mandatory = $true)]
            [string]$SubscriptionName
        )

        $orphanedAssignments = [System.Collections.Generic.List[PSCustomObject]]::new()

        try {
            # Set the subscription context - force execution even in WhatIf mode (we need to switch context to read data)
            $null = Set-AzContext -SubscriptionId $SubscriptionId -ErrorAction Stop -WhatIf:$false

            # Get ALL role assignments within this subscription (includes resource groups and resources)
            # This captures assignments at subscription, resource group, and individual resource level
            Write-Verbose "Fetching all role assignments for subscription: $SubscriptionName (including resource groups and resources)"
            $roleAssignments = @(Get-AzRoleAssignment -ErrorAction Stop)

            # Filter to only assignments that are scoped within this subscription (not inherited from management groups)
            $subscriptionPrefix = "/subscriptions/$SubscriptionId"
            $roleAssignments = @($roleAssignments | Where-Object { $_.Scope -like "$subscriptionPrefix*" })

            Write-Verbose "Found $($roleAssignments.Count) role assignments within subscription scope"

            foreach ($assignment in $roleAssignments) {
                # Debug output for each assignment
                Write-Verbose "Checking: ObjectType='$($assignment.ObjectType)', DisplayName='$($assignment.DisplayName)', ObjectId='$($assignment.ObjectId)', Scope='$($assignment.Scope)'"
                
                # Orphaned assignments have:
                # - ObjectType = 'Unknown' (principal was deleted)
                # - Empty DisplayName (cannot resolve the principal)
                # - DisplayName equals ObjectId (fallback display when principal not found)
                $objectType = [string]$assignment.ObjectType
                $displayName = [string]$assignment.DisplayName
                $objectId = [string]$assignment.ObjectId
                
                $isOrphaned = (
                    $objectType -eq 'Unknown' -or
                    [string]::IsNullOrWhiteSpace($displayName) -or
                    $displayName -eq $objectId
                )

                Write-Verbose "  -> IsOrphaned: $isOrphaned"

                if ($isOrphaned) {
                    $orphanedAssignment = [PSCustomObject]@{
                        SubscriptionId      = $SubscriptionId
                        SubscriptionName    = $SubscriptionName
                        ManagementGroupId   = $null
                        RoleAssignmentId    = $assignment.RoleAssignmentId
                        RoleDefinitionName  = $assignment.RoleDefinitionName
                        Scope               = $assignment.Scope
                        ObjectId            = $objectId
                        ObjectType          = $objectType
                        DisplayName         = $displayName
                        SignInName          = [string]$assignment.SignInName
                    }
                    $orphanedAssignments.Add($orphanedAssignment)
                }
            }
            
            Write-Verbose "Found $($orphanedAssignments.Count) orphaned assignments in this subscription"
        }
        catch {
            Write-Warning "Failed to process subscription '$SubscriptionName' ($SubscriptionId): $_"
        }

        return $orphanedAssignments.ToArray()
    }

    function Get-OrphanedMgmtGroupRoleAssignments {
        <#
        .SYNOPSIS
            Gets orphaned RBAC role assignments for a management group.
        #>
        [CmdletBinding()]
        [OutputType([PSCustomObject[]])]
        param(
            [Parameter(Mandatory = $true)]
            [string]$ManagementGroupId,

            [Parameter(Mandatory = $true)]
            [string]$ManagementGroupName
        )

        $orphanedAssignments = [System.Collections.Generic.List[PSCustomObject]]::new()

        try {
            # Get role assignments at this management group scope
            # Note: No context switch needed for management groups, but we query with scope
            $scope = "/providers/Microsoft.Management/managementGroups/$ManagementGroupId"
            Write-Verbose "Fetching role assignments for management group: $ManagementGroupName at scope: $scope"
            $roleAssignments = @(Get-AzRoleAssignment -Scope $scope -ErrorAction Stop)

            Write-Verbose "Found $($roleAssignments.Count) total role assignments"

            foreach ($assignment in $roleAssignments) {
                Write-Verbose "Checking: ObjectType='$($assignment.ObjectType)', DisplayName='$($assignment.DisplayName)', ObjectId='$($assignment.ObjectId)'"
                
                $objectType = [string]$assignment.ObjectType
                $displayName = [string]$assignment.DisplayName
                $objectId = [string]$assignment.ObjectId
                
                $isOrphaned = (
                    $objectType -eq 'Unknown' -or
                    [string]::IsNullOrWhiteSpace($displayName) -or
                    $displayName -eq $objectId
                )

                Write-Verbose "  -> IsOrphaned: $isOrphaned"

                if ($isOrphaned) {
                    $orphanedAssignment = [PSCustomObject]@{
                        SubscriptionId      = $null
                        SubscriptionName    = "MgmtGroup: $ManagementGroupName"
                        ManagementGroupId   = $ManagementGroupId
                        RoleAssignmentId    = $assignment.RoleAssignmentId
                        RoleDefinitionName  = $assignment.RoleDefinitionName
                        Scope               = $assignment.Scope
                        ObjectId            = $objectId
                        ObjectType          = $objectType
                        DisplayName         = $displayName
                        SignInName          = [string]$assignment.SignInName
                    }
                    $orphanedAssignments.Add($orphanedAssignment)
                }
            }
            
            Write-Verbose "Found $($orphanedAssignments.Count) orphaned assignments in this management group"
        }
        catch {
            Write-Warning "Failed to process management group '$ManagementGroupName' ($ManagementGroupId): $_"
        }

        return $orphanedAssignments.ToArray()
    }

    function Show-OrphanedAssignment {
        <#
        .SYNOPSIS
            Displays details of an orphaned role assignment.
        #>
        [CmdletBinding()]
        param(
            [Parameter(Mandatory = $true)]
            [PSCustomObject]$Assignment,

            [Parameter(Mandatory = $false)]
            [int]$Index = 0,

            [Parameter(Mandatory = $false)]
            [int]$Total = 0
        )

        $indexDisplay = if ($Total -gt 0) { "[$Index/$Total] " } else { "" }
        
        Write-Host ""
        Write-Host "${indexDisplay}Orphaned Role Assignment Found:" -ForegroundColor Yellow
        
        # Show either subscription or management group
        $locationLabel = if ($Assignment.ManagementGroupId) { "  Mgmt Group:      " } else { "  Subscription:    " }
        Write-Host "$locationLabel$($Assignment.SubscriptionName)" -ForegroundColor White
        
        Write-Host "  Role:            $($Assignment.RoleDefinitionName)" -ForegroundColor White
        Write-Host "  Scope:           $($Assignment.Scope)" -ForegroundColor White
        Write-Host "  Object ID:       $($Assignment.ObjectId)" -ForegroundColor DarkGray
        Write-Host "  Object Type:     $($Assignment.ObjectType)" -ForegroundColor DarkGray
        Write-Host "  Assignment ID:   $($Assignment.RoleAssignmentId)" -ForegroundColor DarkGray
    }

    function Remove-OrphanedAssignment {
        <#
        .SYNOPSIS
            Removes an orphaned role assignment.
        #>
        [CmdletBinding(SupportsShouldProcess = $true)]
        [OutputType([bool])]
        param(
            [Parameter(Mandatory = $true)]
            [PSCustomObject]$Assignment,

            [Parameter(Mandatory = $false)]
            [switch]$Force
        )

        $targetDescription = "Role assignment '$($Assignment.RoleDefinitionName)' for object '$($Assignment.ObjectId)' at scope '$($Assignment.Scope)'"

        if ($PSCmdlet.ShouldProcess($targetDescription, "Remove orphaned role assignment")) {
            try {
                # Set context if this is a subscription-level assignment - force execution even in WhatIf mode
                if ($Assignment.SubscriptionId) {
                    $null = Set-AzContext -SubscriptionId $Assignment.SubscriptionId -ErrorAction Stop -WhatIf:$false
                }
                
                # Remove the role assignment using the scope directly
                Remove-AzRoleAssignment -ObjectId $Assignment.ObjectId `
                    -RoleDefinitionName $Assignment.RoleDefinitionName `
                    -Scope $Assignment.Scope `
                    -ErrorAction Stop

                Write-Host "  ✓ Removed successfully" -ForegroundColor Green
                return $true
            }
            catch {
                Write-Host "  ✗ Failed to remove: $_" -ForegroundColor Red
                return $false
            }
        }
        else {
            Write-Host "  → Would remove this assignment (WhatIf mode)" -ForegroundColor Cyan
            return $false
        }
    }

    function Get-UserConfirmation {
        <#
        .SYNOPSIS
            Prompts the user for confirmation with multiple options.
        #>
        [CmdletBinding()]
        [OutputType([string])]
        param(
            [Parameter(Mandatory = $false)]
            [string]$Message = "Do you want to remove this assignment?"
        )

        $validChoices = @('Y', 'N', 'A', 'S')
        
        do {
            Write-Host ""
            Write-Host "$Message" -ForegroundColor Cyan
            Write-Host "  [Y] Yes  [N] No  [A] Yes to All  [S] Skip All remaining: " -NoNewline -ForegroundColor Cyan
            $choice = (Read-Host).Trim().ToUpper()
            
            if ($choice -in $validChoices) {
                return $choice
            }
            Write-Host "  Invalid choice. Please enter Y, N, A, or S." -ForegroundColor Red
        } while ($true)
    }
}

process {
    # Verify Azure connection
    if (-not (Test-AzureConnection)) {
        throw "Azure connection verification failed. Please run 'Connect-AzAccount' and try again."
    }

    # Get subscriptions to process
    Write-Host ""
    Write-Host "Retrieving subscriptions..." -ForegroundColor Cyan

    try {
        if ($SubscriptionId) {
            # Use specified subscriptions
            $subscriptions = @(foreach ($subId in $SubscriptionId) {
                Get-AzSubscription -SubscriptionId $subId -ErrorAction Stop
            })
        }
        else {
            # Get all accessible subscriptions
            $subscriptions = @(Get-AzSubscription -ErrorAction Stop)
        }
    }
    catch {
        throw "Failed to retrieve subscriptions: $_"
    }

    $subscriptionCount = $subscriptions.Count
    if ($subscriptionCount -eq 0) {
        Write-Warning "No subscriptions found or accessible."
        return
    }

    Write-Host "Found $subscriptionCount subscription(s) to scan." -ForegroundColor Green

    # Get management groups if requested
    $managementGroups = @()
    if ($IncludeManagementGroups) {
        Write-Host "Retrieving management groups..." -ForegroundColor Cyan
        try {
            $managementGroups = @(Get-AzManagementGroup -ErrorAction Stop)
            Write-Host "Found $($managementGroups.Count) management group(s) to scan." -ForegroundColor Green
        }
        catch {
            Write-Warning "Failed to retrieve management groups: $_"
        }
    }

    # Phase 1: Collect all orphaned assignments
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Phase 1: Scanning for orphaned role assignments" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan

    # Scan management groups first (if requested)
    if ($managementGroups.Count -gt 0) {
        Write-Host ""
        Write-Host "Scanning Management Groups..." -ForegroundColor Cyan
        Write-Host ("-" * 60) -ForegroundColor DarkGray
        
        $currentMg = 0
        foreach ($mg in $managementGroups) {
            $currentMg++
            $mgName = $mg.DisplayName
            $mgId = $mg.Name

            Write-Host ""
            Write-Host "[$currentMg/$($managementGroups.Count)] Scanning MgmtGroup: $mgName" -ForegroundColor White
            Write-Host "  Management Group ID: $mgId" -ForegroundColor DarkGray

            $orphaned = @(Get-OrphanedMgmtGroupRoleAssignments -ManagementGroupId $mgId -ManagementGroupName $mgName)

            if ($orphaned.Count -gt 0) {
                Write-Host "  Found $($orphaned.Count) orphaned assignment(s)" -ForegroundColor Yellow
                foreach ($item in $orphaned) {
                    $script:AllOrphanedAssignments.Add($item)
                }
            }
            else {
                Write-Host "  No orphaned assignments found" -ForegroundColor Green
            }
        }
    }

    # Scan subscriptions
    Write-Host ""
    Write-Host "Scanning Subscriptions..." -ForegroundColor Cyan
    Write-Host ("-" * 60) -ForegroundColor DarkGray

    $currentSub = 0
    foreach ($subscription in $subscriptions) {
        $currentSub++
        $subName = $subscription.Name
        $subId = $subscription.Id

        Write-Host ""
        Write-Host "[$currentSub/$subscriptionCount] Scanning: $subName" -ForegroundColor White
        Write-Host "  Subscription ID: $subId" -ForegroundColor DarkGray

        $orphaned = @(Get-OrphanedRoleAssignments -SubscriptionId $subId -SubscriptionName $subName)

        if ($orphaned.Count -gt 0) {
            Write-Host "  Found $($orphaned.Count) orphaned assignment(s)" -ForegroundColor Yellow
            foreach ($item in $orphaned) {
                $script:AllOrphanedAssignments.Add($item)
            }
        }
        else {
            Write-Host "  No orphaned assignments found" -ForegroundColor Green
        }
    }

    $script:TotalOrphanedCount = $script:AllOrphanedAssignments.Count

    # Summary of findings
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Scan Complete" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Total orphaned assignments found: $script:TotalOrphanedCount" -ForegroundColor $(if ($script:TotalOrphanedCount -gt 0) { 'Yellow' } else { 'Green' })

    if ($script:TotalOrphanedCount -eq 0) {
        Write-Host ""
        Write-Host "✓ No orphaned role assignments found. Nothing to clean up!" -ForegroundColor Green
        return
    }

    # Display all found orphaned assignments
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Orphaned Assignments Found" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""

    # Group by subscription for cleaner display
    $groupedAssignments = @($script:AllOrphanedAssignments | Group-Object -Property SubscriptionName)

    foreach ($group in $groupedAssignments) {
        Write-Host "Subscription: $($group.Name)" -ForegroundColor Cyan
        Write-Host ("-" * 60) -ForegroundColor DarkGray
        
        $index = 0
        foreach ($assignment in @($group.Group)) {
            $index++
            Write-Host "  [$index] Role:      $($assignment.RoleDefinitionName)" -ForegroundColor White
            Write-Host "      Scope:     $($assignment.Scope)" -ForegroundColor Gray
            Write-Host "      ObjectId:  $($assignment.ObjectId)" -ForegroundColor DarkGray
            Write-Host "      Type:      $($assignment.ObjectType)" -ForegroundColor DarkGray
            Write-Host ""
        }
    }

    # Also output as table for easy copying/export
    Write-Host "Tabular View:" -ForegroundColor Cyan
    @($script:AllOrphanedAssignments) | 
        Select-Object SubscriptionName, RoleDefinitionName, ObjectId, ObjectType, Scope |
        Format-Table -AutoSize -Wrap

    # Phase 2: Process deletions
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Phase 2: Processing orphaned assignments" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan

    $removeAll = $false
    $skipAll = $false
    $currentAssignment = 0

    foreach ($assignment in @($script:AllOrphanedAssignments)) {
        $currentAssignment++
        
        Show-OrphanedAssignment -Assignment $assignment -Index $currentAssignment -Total $script:TotalOrphanedCount

        if ($skipAll) {
            Write-Host "  → Skipped (Skip All selected)" -ForegroundColor DarkGray
            $script:TotalSkippedCount++
            continue
        }

        # Determine if we should proceed with deletion
        $shouldRemove = $false

        if ($WhatIfPreference) {
            # WhatIf mode - just show what would happen
            $shouldRemove = $true
        }
        elseif ($Force -or $removeAll) {
            # Force mode or "Yes to All" selected
            $shouldRemove = $true
        }
        else {
            # Interactive mode - ask user
            $choice = Get-UserConfirmation -Message "Remove this orphaned assignment?"
            
            switch ($choice) {
                'Y' { $shouldRemove = $true }
                'N' { 
                    $shouldRemove = $false 
                    Write-Host "  → Skipped by user" -ForegroundColor DarkGray
                    $script:TotalSkippedCount++
                }
                'A' { 
                    $removeAll = $true 
                    $shouldRemove = $true 
                }
                'S' { 
                    $skipAll = $true 
                    Write-Host "  → Skipped (Skip All selected)" -ForegroundColor DarkGray
                    $script:TotalSkippedCount++
                    continue
                }
            }
        }

        if ($shouldRemove) {
            $removed = Remove-OrphanedAssignment -Assignment $assignment -Force:$Force
            if ($removed) {
                $script:TotalRemovedCount++
            }
            elseif (-not $WhatIfPreference) {
                $script:TotalSkippedCount++
            }
        }
    }
}

end {
    # Final summary
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Summary" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Total orphaned assignments found:   $script:TotalOrphanedCount" -ForegroundColor White
    
    if ($WhatIfPreference) {
        Write-Host "Assignments that would be removed:  $script:TotalOrphanedCount" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Note: Running in WhatIf mode. No changes were made." -ForegroundColor Cyan
    }
    else {
        Write-Host "Assignments removed:                $script:TotalRemovedCount" -ForegroundColor Green
        Write-Host "Assignments skipped:                $script:TotalSkippedCount" -ForegroundColor Yellow
    }
    
    Write-Host ""
    Write-Host "Script completed." -ForegroundColor Green
}
